### ISSUE TITLE
Handle Grayscale Images

### ISSUE THREAD

**Issue by usert5432** [LS4GAN/uvcgan#18]
Our current implementation fails to load grayscale images properly, and always converts them to RGB.

Currently, we are using `torchvision`'s `default_loader` to load images: https://github.com/LS4GAN/uvcgan/blob/0bf89e04967f0951a1cb8429b4331bb0403589c0/uvcgan/data/datasets/funcs.py#L18-L24

However, the `default_loader` func internally does this: https://github.com/pytorch/vision/blob/657027f3548f20aea7b1c34e26511823b1607145/torchvision/datasets/folder.py#L246-L248

That is, it converts all images to RGB, even the grayscale ones. I see at least two ways to fix this issue:
1. Modify our `load_images` function and use a custom image loader. This is a clean solution, but it breaks backward compatibility, so I am a bit on a fence about it.
2. Add another dataset class that will specifically work with grayscale images only (e.g. GrayscaleCycleGANDataset).

@YHRen, could I ask your opinion about this issue please?

Linked issue: https://github.com/LS4GAN/uvcgan/issues/17

**Comment by YHRen** [comment]
@usert5432 
Hmm... maybe check the [mode](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) of the native image after `Image.open(f)`. I'm not sure why you must explicitly convert to RGB. maybe some images are CMYK(?). Maybe convert if an image has more than one channel:
```python
with open(path, "rb") as f:
    img = Image.open(f)
    if img.mode not in {"1", "L", "P", "I", "F"}:
        return img.convert("RGB")
    return img
```

If this is not acceptable, 
I'd suggest to raise an error with a good description once this problem is detected for the main branch considering your current workload at the moment. (maybe try-except the line 19 in `load_images`?) 
The main purpose of this repo is to provide a reference implementation. So option 1 is not good.
We or users can implement option 2 in a different branch for the time being.
What do you think?

**Comment by usert5432** [comment]
Hi @YHRen,

Thank you for your feedback!

> Hmm... maybe check the [mode](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) of the native image after Image.open(f). I'm not sure why you must explicitly convert to RGB. maybe some images are CMYK(?).

I guess it may be useful to convert CMYK to RBG, since color augmentations and DL methods are developed mostly (?) for RGB images.

> Maybe convert if an image has more than one channel:

This looks good. Thank you @YHRen !

> I'd suggest to raise an error with a good description once this problem is detected for the main branch considering your current workload at the moment. (maybe try-except the line 19 in load_images?)
> The main purpose of this repo is to provide a reference implementation. So option 1 is not good.
> We or users can implement option 2 in a different branch for the time being.
> What do you think?

Makes sense. I think I will send a PR with a new dataset shortly (it should not be difficult).
